global: 
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins:8080']
    scrape_interval: 30s

  - job_name: 'time-tracker'
    static_configs:
      - targets: 
          - 'tracker:5173'
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'windows-host'
    static_configs:
      - targets: ['host.docker.internal:9182']
    scrape_interval: 30s
    metrics_path: '/metrics'
